/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator_app;

import java.awt.event.KeyEvent;

/**
 *
 * @author nassimabenbahtane
 */
public class Scientific_Mode extends javax.swing.JFrame {

    
    double ans,num;
    /**
     * Creates new form Scientific_Mode
     */
    public Scientific_Mode() {
        initComponents();
    }
    
    public String Display_doubleORint(double ans){ 
        String result;
        if ((ans % 1) == 0) {
            result = Integer.toString((int) ans);
        }else{
            result = Double.toString(ans);
        }
        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PlusMinus_ = new javax.swing.JButton();
        jButton4_ = new javax.swing.JButton();
        Equal_ = new javax.swing.JButton();
        jButton5_ = new javax.swing.JButton();
        DisplayField = new javax.swing.JTextField();
        jButton6_ = new javax.swing.JButton();
        AC_ = new javax.swing.JButton();
        Minus = new javax.swing.JButton();
        Del_ = new javax.swing.JButton();
        jButton1_ = new javax.swing.JButton();
        modulo_ = new javax.swing.JButton();
        jButton2_ = new javax.swing.JButton();
        Div_ = new javax.swing.JButton();
        jButton3_ = new javax.swing.JButton();
        jButton7_ = new javax.swing.JButton();
        Add_ = new javax.swing.JButton();
        jButton8_ = new javax.swing.JButton();
        jButton0_ = new javax.swing.JButton();
        jButton9_ = new javax.swing.JButton();
        Point_ = new javax.swing.JButton();
        Mul_ = new javax.swing.JButton();
        jButton6_1 = new javax.swing.JButton();
        AC_1 = new javax.swing.JButton();
        sin_ = new javax.swing.JButton();
        sinh_ = new javax.swing.JButton();
        Div_1 = new javax.swing.JButton();
        Minus1 = new javax.swing.JButton();
        sqrt_ = new javax.swing.JButton();
        jButton2_1 = new javax.swing.JButton();
        PI_ = new javax.swing.JButton();
        jButton7_1 = new javax.swing.JButton();
        E_ = new javax.swing.JButton();
        cos_ = new javax.swing.JButton();
        jButton0_1 = new javax.swing.JButton();
        jButton9_1 = new javax.swing.JButton();
        Point_1 = new javax.swing.JButton();
        Mul_1 = new javax.swing.JButton();
        PlusMinus_1 = new javax.swing.JButton();
        log_ = new javax.swing.JButton();
        Equal_1 = new javax.swing.JButton();
        tan_ = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        Normal = new javax.swing.JMenuItem();
        Scientific = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PlusMinus_.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        PlusMinus_.setText("+/-");
        PlusMinus_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusMinus_ActionPerformed(evt);
            }
        });

        jButton4_.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButton4_.setText("4");
        jButton4_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_ActionPerformed(evt);
            }
        });

        Equal_.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        Equal_.setText("=");
        Equal_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Equal_ActionPerformed(evt);
            }
        });

        jButton5_.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButton5_.setText("5");
        jButton5_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5_ActionPerformed(evt);
            }
        });

        DisplayField.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        DisplayField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        DisplayField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayFieldActionPerformed(evt);
            }
        });
        DisplayField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DisplayFieldKeyTyped(evt);
            }
        });

        jButton6_.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButton6_.setText("6");
        jButton6_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6_ActionPerformed(evt);
            }
        });

        AC_.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        AC_.setText("AC");
        AC_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AC_ActionPerformed(evt);
            }
        });

        Minus.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        Minus.setText("-");

        Del_.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        Del_.setText("Del");
        Del_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Del_ActionPerformed(evt);
            }
        });

        jButton1_.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButton1_.setText("1");
        jButton1_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_ActionPerformed(evt);
            }
        });

        modulo_.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        modulo_.setText("%");

        jButton2_.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButton2_.setText("2");
        jButton2_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_ActionPerformed(evt);
            }
        });

        Div_.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        Div_.setText("÷");

        jButton3_.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButton3_.setText("3");
        jButton3_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_ActionPerformed(evt);
            }
        });

        jButton7_.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButton7_.setText("7");
        jButton7_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7_ActionPerformed(evt);
            }
        });

        Add_.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        Add_.setText("+");
        Add_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_ActionPerformed(evt);
            }
        });

        jButton8_.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButton8_.setText("8");
        jButton8_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8_ActionPerformed(evt);
            }
        });

        jButton0_.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButton0_.setText("0");
        jButton0_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0_ActionPerformed(evt);
            }
        });

        jButton9_.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButton9_.setText("9");
        jButton9_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9_ActionPerformed(evt);
            }
        });

        Point_.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        Point_.setText(",");
        Point_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Point_ActionPerformed(evt);
            }
        });

        Mul_.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        Mul_.setText("x");

        jButton6_1.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        jButton6_1.setText("tanh");

        AC_1.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        AC_1.setText("x!");

        sin_.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        sin_.setText("sin");
        sin_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sin_ActionPerformed(evt);
            }
        });

        sinh_.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        sinh_.setText("sinh");
        sinh_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sinh_ActionPerformed(evt);
            }
        });

        Div_1.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        Div_1.setText("x^2");

        Minus1.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        Minus1.setText("10^x");

        sqrt_.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        sqrt_.setText("√x");
        sqrt_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrt_ActionPerformed(evt);
            }
        });

        jButton2_1.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        jButton2_1.setText("EXP");

        PI_.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        PI_.setText("π");
        PI_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PI_ActionPerformed(evt);
            }
        });

        jButton7_1.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButton7_1.setText("ln");

        E_.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        E_.setText("E");
        E_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_ActionPerformed(evt);
            }
        });

        cos_.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        cos_.setText("cos");
        cos_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cos_ActionPerformed(evt);
            }
        });

        jButton0_1.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        jButton0_1.setText("x^y");

        jButton9_1.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        jButton9_1.setText("cosh");

        Point_1.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        Point_1.setText("(");

        Mul_1.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        Mul_1.setText("x^3");

        PlusMinus_1.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        PlusMinus_1.setText(")");

        log_.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        log_.setText("log");
        log_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_ActionPerformed(evt);
            }
        });

        Equal_1.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        Equal_1.setText("Rnd");

        tan_.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        tan_.setText("tan");
        tan_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tan_ActionPerformed(evt);
            }
        });

        jMenu5.setText("Mode");

        Normal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Normal.setText("Normal Mode");
        Normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NormalActionPerformed(evt);
            }
        });
        jMenu5.add(Normal);

        Scientific.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Scientific.setText("Scientific Mode");
        Scientific.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScientificActionPerformed(evt);
            }
        });
        jMenu5.add(Scientific);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(DisplayField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1_, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2_, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3_, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Add_, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton7_, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton8_, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton9_, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mul_, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(AC_, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Del_, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(modulo_, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Div_, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton4_, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton5_, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton6_, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Minus, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton0_, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Point_, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PlusMinus_, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Equal_, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton0_1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Point_1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PlusMinus_1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Equal_1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton7_1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cos_, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton9_1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Mul_1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(AC_1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sin_, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sinh_, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Div_1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(log_, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tan_, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton6_1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Minus1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sqrt_, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PI_, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E_, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(DisplayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AC_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Del_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modulo_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Div_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Mul_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Minus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Add_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton0_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Point_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PlusMinus_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Equal_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AC_1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sin_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sinh_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Div_1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7_1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cos_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9_1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Mul_1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(log_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tan_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6_1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Minus1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sqrt_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PI_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E_, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton0_1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Point_1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PlusMinus_1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Equal_1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlusMinus_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusMinus_ActionPerformed
        if (DisplayField.getText().length() > 0) {
            num = Double.parseDouble(DisplayField.getText());
            ans = num * (-1);
            DisplayField.setText(Display_doubleORint(ans));
        }else{
            DisplayField.setText("-");
        }
    }//GEN-LAST:event_PlusMinus_ActionPerformed

    private void jButton4_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_ActionPerformed
        DisplayField.setText(DisplayField.getText() + "4");
    }//GEN-LAST:event_jButton4_ActionPerformed

    private void Equal_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Equal_ActionPerformed

    }//GEN-LAST:event_Equal_ActionPerformed

    private void jButton5_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5_ActionPerformed
        DisplayField.setText(DisplayField.getText() + "5");
    }//GEN-LAST:event_jButton5_ActionPerformed

    private void DisplayFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayFieldActionPerformed

    private void DisplayFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DisplayFieldKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)) || (c==KeyEvent.VK_BACK_SPACE) || (c==KeyEvent.VK_DELETE) ){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_DisplayFieldKeyTyped

    private void jButton6_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6_ActionPerformed
        DisplayField.setText(DisplayField.getText() + "6");
    }//GEN-LAST:event_jButton6_ActionPerformed

    private void AC_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AC_ActionPerformed
        DisplayField.setText("0");
    }//GEN-LAST:event_AC_ActionPerformed

    private void Del_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Del_ActionPerformed
        if (DisplayField.getText().length() > 0){                            // Make sure the text feide aint empty
            StringBuilder text = new StringBuilder(DisplayField.getText());  // fill the buffer with the String input
            text.deleteCharAt(DisplayField.getText().length() - 1);          // delete the character at the last index
            DisplayField.setText(text.toString());               // convert the result back to a String and display it
        }
    }//GEN-LAST:event_Del_ActionPerformed

    private void jButton1_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_ActionPerformed
        DisplayField.setText(DisplayField.getText() + "1");
    }//GEN-LAST:event_jButton1_ActionPerformed

    private void jButton2_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_ActionPerformed
        DisplayField.setText(DisplayField.getText() + "2");
    }//GEN-LAST:event_jButton2_ActionPerformed

    private void jButton3_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_ActionPerformed
        DisplayField.setText(DisplayField.getText() + "3");
    }//GEN-LAST:event_jButton3_ActionPerformed

    private void jButton7_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7_ActionPerformed
        DisplayField.setText(DisplayField.getText() + "7");
    }//GEN-LAST:event_jButton7_ActionPerformed

    private void Add_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_ActionPerformed

    }//GEN-LAST:event_Add_ActionPerformed

    private void jButton8_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8_ActionPerformed
        DisplayField.setText(DisplayField.getText() + "8");
    }//GEN-LAST:event_jButton8_ActionPerformed

    private void jButton0_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0_ActionPerformed
        DisplayField.setText(DisplayField.getText() + "0");
    }//GEN-LAST:event_jButton0_ActionPerformed

    private void jButton9_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9_ActionPerformed
        DisplayField.setText(DisplayField.getText() + "9");
    }//GEN-LAST:event_jButton9_ActionPerformed

    private void Point_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Point_ActionPerformed
        if (DisplayField.getText().length() > 0) {
            DisplayField.setText(DisplayField.getText() + ".");
        }else{
            DisplayField.setText("0.");
        }
    }//GEN-LAST:event_Point_ActionPerformed

    private void NormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NormalActionPerformed
        this.dispose();
        Normal_Mode obj = new Normal_Mode();
        obj.setVisible(true);
    }//GEN-LAST:event_NormalActionPerformed

    private void ScientificActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScientificActionPerformed

    }//GEN-LAST:event_ScientificActionPerformed

    private void sin_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sin_ActionPerformed
//
//        if (DisplayField.getText().length() > 0) {
//            num1 = Double.parseDouble(DisplayField.getText());
//            ans = Math.sin(num1);
//            jLabel1.setText("sin("+DisplayField.getText()+")");
//            DisplayField.setText(Double.toString(ans));
//        }else{
//            jLabel1.setText("sin(");
//        }
    }//GEN-LAST:event_sin_ActionPerformed

    private void sinh_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sinh_ActionPerformed

//        if (DisplayField.getText().length() > 0) {
//            num1 = Double.parseDouble(DisplayField.getText());
//            ans = Math.sinh(num1);
//            jLabel1.setText("sinh("+DisplayField.getText()+")");
//            DisplayField.setText(Double.toString(ans));
//        }else{
//            jLabel1.setText("sinh(");
//        }
    }//GEN-LAST:event_sinh_ActionPerformed

    private void sqrt_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrt_ActionPerformed
//        if (DisplayField.getText().length() > 0) {
//            num1 = Double.parseDouble(DisplayField.getText());
//            ans = Math.sqrt(num1);
//            jLabel1.setText("sqrt("+DisplayField.getText()+")");
//            DisplayField.setText(Double.toString(ans));
//        }else{
//            jLabel1.setText("sqrt(");
//        }
    }//GEN-LAST:event_sqrt_ActionPerformed

    private void PI_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PI_ActionPerformed
        //        symb = 2;
        //        DisplayField.setText(DisplayField.getText() + Math.PI);
    }//GEN-LAST:event_PI_ActionPerformed

    private void E_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_ActionPerformed
        //        symb = 1;
        //        DisplayField.setText(DisplayField.getText() +"E");
    }//GEN-LAST:event_E_ActionPerformed

    private void cos_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cos_ActionPerformed
//        if (DisplayField.getText().length() > 0) {
//            num1 = Double.parseDouble(DisplayField.getText());
//            ans = Math.cos(num1);
//            jLabel1.setText("cos("+DisplayField.getText()+")");
//            DisplayField.setText(Double.toString(ans));
//        }else{
//            jLabel1.setText("cos(");
//        }
    }//GEN-LAST:event_cos_ActionPerformed

    private void log_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_ActionPerformed

//        if (DisplayField.getText().length() > 0) {
//            num = Double.parseDouble(DisplayField.getText());
//            ans = Math.log(num1);
//            jLabel1.setText("log("+DisplayField.getText()+")");
//            DisplayField.setText(Double.toString(ans));
//        }else{
//            jLabel1.setText("log(");
//        }
    }//GEN-LAST:event_log_ActionPerformed

    private void tan_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tan_ActionPerformed
//        if (DisplayField.getText().length() > 0) {
//            num1 = Double.parseDouble(DisplayField.getText());
//            ans = Math.tan(num1);
//            jLabel1.setText("tan("+DisplayField.getText()+")");
//            DisplayField.setText(Double.toString(ans));
//        }else{
//            jLabel1.setText("tan(");
//        }
    }//GEN-LAST:event_tan_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Scientific_Mode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Scientific_Mode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Scientific_Mode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Scientific_Mode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Scientific_Mode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AC_;
    private javax.swing.JButton AC_1;
    private javax.swing.JButton Add_;
    private javax.swing.JButton Del_;
    private javax.swing.JTextField DisplayField;
    private javax.swing.JButton Div_;
    private javax.swing.JButton Div_1;
    private javax.swing.JButton E_;
    private javax.swing.JButton Equal_;
    private javax.swing.JButton Equal_1;
    private javax.swing.JButton Minus;
    private javax.swing.JButton Minus1;
    private javax.swing.JButton Mul_;
    private javax.swing.JButton Mul_1;
    private javax.swing.JMenuItem Normal;
    private javax.swing.JButton PI_;
    private javax.swing.JButton PlusMinus_;
    private javax.swing.JButton PlusMinus_1;
    private javax.swing.JButton Point_;
    private javax.swing.JButton Point_1;
    private javax.swing.JMenuItem Scientific;
    private javax.swing.JButton cos_;
    private javax.swing.JButton jButton0_;
    private javax.swing.JButton jButton0_1;
    private javax.swing.JButton jButton1_;
    private javax.swing.JButton jButton2_;
    private javax.swing.JButton jButton2_1;
    private javax.swing.JButton jButton3_;
    private javax.swing.JButton jButton4_;
    private javax.swing.JButton jButton5_;
    private javax.swing.JButton jButton6_;
    private javax.swing.JButton jButton6_1;
    private javax.swing.JButton jButton7_;
    private javax.swing.JButton jButton7_1;
    private javax.swing.JButton jButton8_;
    private javax.swing.JButton jButton9_;
    private javax.swing.JButton jButton9_1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton log_;
    private javax.swing.JButton modulo_;
    private javax.swing.JButton sin_;
    private javax.swing.JButton sinh_;
    private javax.swing.JButton sqrt_;
    private javax.swing.JButton tan_;
    // End of variables declaration//GEN-END:variables
}
